apiVersion: v1
kind: Service
metadata:
  name: convert
  labels:
    run: convert
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    run: convert
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convert
spec:
  selector:
    matchLabels:
      run: convert
  replicas: 1
  template:
    metadata:
      labels:
        run: convert
    spec:
      containers:
        - name: convert-container
          image: srgmaildocker/convert:v.0.0.3
          env:
            - name: PORT
              value: '80'
            - name: Exchange_Domain
              value: 'http://exchange'
          ports:
            - containerPort: 80