apiVersion: v1
kind: Service
metadata:
  name: convert
  labels:
    run: convert
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    run: convert
